### ISSUE TITLE
Please elaborate on pelicanconf.py settings

### ISSUE THREAD

**Issue by royemmerich** [cocodelabs/cocode.org#6]
Kyle the way you have set up the cocode Pelican blog is exactly what I am trying to do for my own site (www.infinitefingers.com). I want a static home page and the blog posts should be saved under a `blog` folder. Achieving this is easy. What I am struggling with is how to get the blog's paginated `index.html` pages to be saved under the `blog` folder.

I am specifically curious about the following settings in your `pelicanconf.py` file:

``` python
BLOG_URL = 'blog/'
BLOG_INDEX_SAVE_AS = 'blog/index.html'
```

Are these new, undocumented setting options or have you modified the core pelican software?

Your help would be greatly appreciated.

**Comment by leotrs** [comment]
This can be closed.
